# Generated by Django 4.2.1 on 2023-06-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrickApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snombre', models.TextField()),
                ('stalla', models.TextField()),
                ('cantidad', models.TextField()),
                ('genero', models.TextField()),
            ],
        ),
    ]
