# Generated by Django 4.2.1 on 2023-07-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebrickApp', '0002_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=60)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('talla', models.IntegerField()),
                ('genero', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Zapatilla',
        ),
    ]
